require "active_model"
require "g5_integrations_validations/version"
require "g5_integrations_validations/centershift_inventory_validations"
require "g5_integrations_validations/centershift_cta_url_validations"
require "g5_integrations_validations/site_link_inventory_validations"
require "g5_integrations_validations/site_link_inventory_cta_threshold_validations"
require "g5_integrations_validations/site_link_inventory_cta_url_validations"
require "g5_integrations_validations/site_link_inventory_presence_validations"
require "g5_integrations_validations/site_link_lead_validations"
require "g5_integrations_validations/rate_validations"
require "g5_integrations_validations/yardi_voyager_lead_validations"
require "g5_integrations_validations/yardi_voyager_inventory_validations"
require "g5_integrations_validations/yardi_voyager_inventory_cta_threshold_validations"
require "g5_integrations_validations/yardi_voyager_inventory_cta_url_validations"
require "g5_integrations_validations/yardi_voyager_inventory_rate_source_validations"

module G5IntegrationsValidations
end
