require "active_model"
require "g5_integrations_validations/version"
require "g5_integrations_validations/site_link_inventory_validations"
require "g5_integrations_validations/site_link_lead_validations"

module G5IntegrationsValidations
end
